services:
  tdf:
    image: gregmika/temps_de_funcionament:v1.1-amd64
    container_name: tdf
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./example-config.yaml:/etc/temps_de_funcionament/config.yaml:ro
